# Generated by Django 3.2.9 on 2021-12-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('M', 'MOBILE'), ('L', 'LAPTOP'), ('TW', 'Top wear'), ('BW', 'bottom wear')], max_length=2)),
                ('product_img', models.ImageField(upload_to='productimages')),
            ],
        ),
    ]
